#!/bin/bash
# Testing script for Booking to Payments Navigation

echo "═════════════════════════════════════════════════════════════"
echo "  BOOKING TO PAYMENTS NAVIGATION - TESTING SCRIPT"
echo "═════════════════════════════════════════════════════════════"
echo ""

echo "✅ STEP 1: Check if backend is running"
echo "─────────────────────────────────────────────────────────────"
echo ""
echo "Testing: curl http://localhost:4000/bookings"
echo ""
echo "If you see connection error, run in new terminal:"
echo "  cd d:\IMS\IMSBackend"
echo "  npm start"
echo ""
echo "Press Enter to continue..."
read

echo ""
echo "✅ STEP 2: Clear app cache and restart"
echo "─────────────────────────────────────────────────────────────"
echo ""
echo "Running: npx expo start -c"
echo ""
echo "This will:"
echo "  1. Clear the Expo cache"
echo "  2. Start the development server"
echo "  3. Give you options to run on Android/iOS emulator"
echo ""
echo "Instructions:"
echo "  - Wait for 'Press a|i|w|c|q to open' message"
echo "  - Press 'a' for Android emulator"
echo "  - Press 'i' for iOS simulator"
echo ""
echo "Then follow the next steps while app is running..."
echo ""

cd d:\IMS\app1
npx expo start -c

echo ""
echo "✅ STEP 3: Test the Booking Flow"
echo "─────────────────────────────────────────────────────────────"
echo ""
echo "While the app is running:"
echo ""
echo "1. Open browser console (F12 → Console tab)"
echo "2. In the app:"
echo "   a) Go to Packages tab"
echo "   b) Select any package"
echo "   c) Click 'Book Now'"
echo "   d) Fill booking details"
echo "   e) Click 'Complete Booking'"
echo ""
echo "3. Watch the console for these logs:"
echo "   ✓ [Booking] SUCCESS! Booking created successfully"
echo "   ✓ [Booking] Extracted bookingId: XXX"
echo "   ✓ [Booking] Parent navigator exists: true"
echo "   ✓ [Booking] ========== NAVIGATION STARTING =========="
echo "   ✓ [Payments] Page loaded. route.params: {bookingId: XXX}"
echo ""
echo "4. In the app:"
echo "   → Alert should show 'Booking Confirmed'"
echo "   → Click 'Proceed to Payment'"
echo "   → App should switch to Payments tab"
echo "   → Should see payment form"
echo ""
echo "─────────────────────────────────────────────────────────────"
echo ""
echo "Expected sequence in console:"
echo ""
echo "  [Booking] SUCCESS! Booking created successfully"
echo "  [Booking] Extracted bookingId: 126"
echo "  [Booking] Booking created successfully. bookingId: 126"
echo "  [Booking] Parent navigator exists: true"
echo "  [Booking] Navigation object type: tab"
echo "  → Alert popup appears in app"
echo "  → User clicks 'Proceed to Payment'"
echo "  [Booking] ========== NAVIGATION STARTING =========="
echo "  [Booking] Attempting navigation with parent: true"
echo "  [Booking] Using parent.navigate() to go to Payments tab"
echo "  [Booking] ========== NAVIGATION CALL MADE =========="
echo "  [Payments] Page loaded. route.params: {bookingId: 126}"
echo "  [Payments] Extracted bookingId: 126"
echo "  [Payments] Calling bookingAPI.getById(126)"
echo "  [Payments] ✅ Booking details loaded: {...}"
echo ""
echo "If you see this sequence → SUCCESS! ✅"
echo ""
echo "─────────────────────────────────────────────────────────────"
echo ""
echo "If navigation doesn't happen, check for:"
echo ""
echo "❌ Parent navigator exists: false"
echo "   → Problem with navigation structure"
echo "   → Check App.js Tab.Navigator setup"
echo ""
echo "❌ No navigation logs at all"
echo "   → onPress handler isn't executing"
echo "   → Try: Clear cache completely"
echo ""
echo "❌ Navigation error: [message]"
echo "   → There's an issue with the nav params"
echo "   → Send me the error message"
echo ""
echo "❌ Failed to fetch booking details"
echo "   → Backend not returning booking"
echo "   → Check: mysql Fin -e \"SELECT * FROM bookings LIMIT 1;\""
echo ""
echo "─────────────────────────────────────────────────────────────"
echo ""
echo "DEBUGGING TIPS:"
echo ""
echo "1. Open browser console (F12)"
echo "2. Type in console:"
echo "   → Look for [Booking] logs"
echo "   → Look for [Payments] logs"
echo ""
echo "3. Take screenshot of console output"
echo ""
echo "4. If stuck, send me:"
echo "   → Screenshot of console"
echo "   → Screenshot of alert"
echo "   → Description of what happens"
echo ""
echo "═════════════════════════════════════════════════════════════"
echo ""
